"""
Budget Service Unit Tests
Comprehensive coverage of all business logic, edge cases, and error paths.
Run with: pytest tests/test_services/test_budget_service.py -v
"""
import pytest
import uuid
from decimal import Decimal
from datetime import datetime, timezone, timedelta
from unittest.mock import MagicMock, patch
from dateutil.relativedelta import relativedelta

from app.models.budget import Budget, BudgetPeriod, BillRecurrence, BillStatus
from app.models.user import User
from app.models.notification import Notification, NotificationType, NotificationPriority
from app.models.category import Category
from app.utils.budget_helpers import advance_bill_cycle
from app.services.budget_service import BudgetService
from app.schemas.budget import (
    BudgetCreate, BudgetUpdate, BudgetProgressResponse, 
    BudgetAlertResponse
)
from app.core.exceptions import CategoryNotFoundException, BudgetAlreadyExistsException


# ─── Helpers ────────────────────────────────────────────────────────────────

def make_user(spending_limit=None, threshold=80, spending_period=BudgetPeriod.MONTHLY):
    user = MagicMock(spec=User)
    user.user_id = uuid.uuid4()
    user.spending_limit = spending_limit
    user.threshold = threshold
    user.spending_period = spending_period
    return user

def make_category(category_id=None, name="Test Category", parent_id=None):
    cat = MagicMock(spec=Category)
    cat.category_id = category_id or uuid.uuid4()
    cat.name = name
    cat.parent_id = parent_id
    cat.is_active = True
    cat.display_order = 1
    return cat

def make_budget(is_bill=False, status=BillStatus.PENDING):
    budget = MagicMock(spec=Budget)
    budget.budget_id = uuid.uuid4()
    budget.category_id = uuid.uuid4()
    budget.is_bill = is_bill
    budget.bill_name = "Test Bill" if is_bill else None
    budget.bill_status = status
    budget.due_date = datetime.now(timezone.utc) + timedelta(days=5)
    budget.last_paid_at = None
    return budget

def mock_refresh(obj):
    """Simulate SQLAlchemy refresh() populating autogenerated fields."""
    obj.budget_id = uuid.uuid4()
    obj.created_at = datetime.now(timezone.utc)

# ══════════════════════════════════════════════════════════════════════════════
# TestCreateBudget
# ══════════════════════════════════════════════════════════════════════════════

class TestCreateBudget:
    def test_create_budget_success(self):
        """Validates that a budget is successfully created when category exists and no overlap occurs."""
        db = MagicMock()
        service = BudgetService(db)
        user_id = uuid.uuid4()
        cat_id = uuid.uuid4()
        
        db.query.return_value.filter.return_value.first.side_effect = [
            make_category(cat_id), None
        ]
        db.add = MagicMock()
        db.commit = MagicMock()
        db.refresh.side_effect = mock_refresh
        
        start = datetime.now(timezone.utc)
        # Schema requires end_date, so we must provide a valid one
        data = BudgetCreate(
            category_id=cat_id, 
            amount=Decimal("100.00"), 
            period=BudgetPeriod.MONTHLY,
            start_date=start, 
            end_date=start + timedelta(days=30), 
            is_bill=False
        )
        
        result = service.create_budget(user_id, data)
        
        assert result.amount == Decimal("100.00")
        db.add.assert_called_once()
        db.commit.assert_called_once()

    def test_create_budget_category_not_found(self):
        """Ensures CategoryNotFoundException is raised when the specified category doesn't exist."""
        db = MagicMock()
        service = BudgetService(db)
        db.query.return_value.filter.return_value.first.return_value = None
        
        start = datetime.now(timezone.utc)
        data = BudgetCreate(
            category_id=uuid.uuid4(), amount=Decimal("100.00"), period=BudgetPeriod.MONTHLY,
            start_date=start, end_date=start + timedelta(days=30), is_bill=False
        )
        
        with pytest.raises(CategoryNotFoundException):
            service.create_budget(uuid.uuid4(), data)

    def test_create_budget_overlap_raises_error(self):
        """Verifies that BudgetAlreadyExistsException is raised when an overlapping budget exists."""
        db = MagicMock()
        service = BudgetService(db)
        cat_id = uuid.uuid4()
        
        db.query.return_value.filter.return_value.first.side_effect = [
            make_category(cat_id), make_budget()
        ]
        
        start = datetime.now(timezone.utc)
        data = BudgetCreate(
            category_id=cat_id, amount=Decimal("100.00"), period=BudgetPeriod.MONTHLY,
            start_date=start, end_date=start + timedelta(days=30), is_bill=False
        )
        
        with pytest.raises(BudgetAlreadyExistsException):
            service.create_budget(uuid.uuid4(), data)

    def test_create_budget_with_december_start_date(self):
        """Tests that a budget starting in December is successfully created with a valid end date."""
        db = MagicMock()
        service = BudgetService(db)
        cat_id = uuid.uuid4()
        
        db.query.return_value.filter.return_value.first.side_effect = [make_category(cat_id), None]
        db.add = MagicMock()
        db.commit = MagicMock()
        db.refresh.side_effect = mock_refresh
        
        start = datetime(2026, 12, 15, tzinfo=timezone.utc)
        # Schema requires end_date, so we provide the calculated rollover date
        end = datetime(2027, 1, 31, 23, 59, 59, 999999, tzinfo=timezone.utc)
        data = BudgetCreate(
            category_id=cat_id, amount=Decimal("100.00"), period=BudgetPeriod.MONTHLY,
            start_date=start, end_date=end, is_bill=False
        )
        
        result = service.create_budget(uuid.uuid4(), data)
        
        assert result.end_date.month == 1
        assert result.end_date.year == 2027


# ══════════════════════════════════════════════════════════════════════════════
# TestCalculateBudgetProgress
# ══════════════════════════════════════════════════════════════════════════════

class TestCalculateBudgetProgress:
    def _run(self, spent, spending_limit, threshold=80):
        db = MagicMock()
        user = make_user(spending_limit=spending_limit, threshold=threshold)
        service = BudgetService(db)

        with patch("app.services.budget_service.get_user_by_id", return_value=user), \
             patch("app.services.budget_service.get_period_dates", return_value=(
                 datetime(2026, 3, 1, tzinfo=timezone.utc),
                 datetime(2026, 3, 31, tzinfo=timezone.utc),
             )), \
             patch.object(service, "_calculate_total_period_spending", return_value=Decimal(str(spent))):
            return service.calculate_budget_progress(user.user_id, BudgetPeriod.MONTHLY)

    def test_on_track(self):
        """Confirms status is 'on_track' when spending is well below the threshold."""
        result = self._run(spent=2000, spending_limit=Decimal("10000.00"))
        assert result.status == "on_track"
        assert result.remaining == Decimal("8000.00")

    def test_exactly_at_threshold(self):
        """Validates that spending exactly at the threshold (80%) triggers 'warning' status."""
        result = self._run(spent=8000, spending_limit=Decimal("10000.00"), threshold=80)
        assert result.status == "warning"

    def test_exceeded_caps_remaining_at_zero(self):
        """Ensures remaining amount never goes negative, capping at 0.00 when budget is exceeded."""
        result = self._run(spent=15000, spending_limit=Decimal("10000.00"))
        assert result.status == "exceeded"
        assert result.remaining == Decimal("0.00")

    def test_zero_spending_limit_avoids_division_by_zero(self):
        """Prevents ZeroDivisionError when spending limit is set to 0.00."""
        result = self._run(spent=5000, spending_limit=Decimal("0.00"))
        assert result.status == "on_track"
        assert result.percentage == 0.0

    def test_none_spending_limit_defaults_to_zero(self):
        """Handles the case where spending_limit is None by defaulting to 0.00."""
        result = self._run(spent=5000, spending_limit=None)
        assert result.status == "on_track"
        assert result.spending_limit == Decimal("0.00")


# ══════════════════════════════════════════════════════════════════════════════
# TestCheckOrCreateBudgetNotification
# ══════════════════════════════════════════════════════════════════════════════

class TestCheckOrCreateBudgetNotification:
    def test_returns_zero_if_no_spending_limit(self):
        """Returns 0 alerts created when user has no spending limit set."""
        db = MagicMock()
        user = make_user(spending_limit=None)
        service = BudgetService(db)
        
        # Must mock get_user_by_id to return our configured user mock
        with patch("app.services.budget_service.get_user_by_id", return_value=user):
            assert service.check_or_create_budget_notification(user.user_id) == 0

    def test_returns_zero_if_spending_limit_is_zero(self):
        """Returns 0 alerts created when spending limit is explicitly set to 0.00."""
        db = MagicMock()
        user = make_user(spending_limit=Decimal("0.00"))
        service = BudgetService(db)
        
        with patch("app.services.budget_service.get_user_by_id", return_value=user):
            assert service.check_or_create_budget_notification(user.user_id) == 0

    def test_creates_exceeded_notification(self):
        """Creates an URGENT notification when spending exceeds 100% of the budget."""
        db = MagicMock()
        user = make_user(spending_limit=Decimal("100.00"), threshold=80)
        service = BudgetService(db)
        
        with patch("app.services.budget_service.get_user_by_id", return_value=user), \
             patch("app.services.budget_service.get_period_dates", return_value=(
                 datetime(2026, 3, 1, tzinfo=timezone.utc), datetime(2026, 3, 31, tzinfo=timezone.utc)
             )), \
             patch("app.services.notification_service.NotificationService.create_notification") as mock_create:
            
            mock_query = MagicMock()
            mock_query.filter.return_value.scalar.return_value = Decimal("150.00")
            db.query.return_value = mock_query
            
            service._alert_already_sent = MagicMock(return_value=False)
            
            result = service.check_or_create_budget_notification(user.user_id)
            
            assert result == 1
            mock_create.assert_called_once()
            call_kwargs = mock_create.call_args.kwargs
            assert call_kwargs["priority"] == NotificationPriority.URGENT
            assert "150.0%" in call_kwargs["message"]

    def test_creates_warning_notification_at_custom_threshold(self):
        """Creates a NORMAL priority notification when spending reaches a custom threshold (90%)."""
        db = MagicMock()
        user = make_user(spending_limit=Decimal("100.00"), threshold=90)
        service = BudgetService(db)
        
        with patch("app.services.budget_service.get_user_by_id", return_value=user), \
             patch("app.services.budget_service.get_period_dates", return_value=(
                 datetime(2026, 3, 1, tzinfo=timezone.utc), datetime(2026, 3, 31, tzinfo=timezone.utc)
             )), \
             patch("app.services.notification_service.NotificationService.create_notification") as mock_create:
            
            mock_query = MagicMock()
            mock_query.filter.return_value.scalar.return_value = Decimal("95.00")
            db.query.return_value = mock_query
            
            service._alert_already_sent = MagicMock(return_value=False)
            
            result = service.check_or_create_budget_notification(user.user_id)
            
            assert result == 1
            call_kwargs = mock_create.call_args.kwargs
            assert call_kwargs["priority"] == NotificationPriority.NORMAL

    def test_does_not_create_notification_below_threshold(self):
        """Ensures no notification is created when spending is below the threshold."""
        db = MagicMock()
        user = make_user(spending_limit=Decimal("100.00"), threshold=80)
        service = BudgetService(db)
        
        with patch("app.services.budget_service.get_user_by_id", return_value=user), \
             patch("app.services.budget_service.get_period_dates", return_value=(
                 datetime(2026, 3, 1, tzinfo=timezone.utc), datetime(2026, 3, 31, tzinfo=timezone.utc)
             )), \
             patch("app.services.notification_service.NotificationService.create_notification") as mock_create:
            
            mock_query = MagicMock()
            mock_query.filter.return_value.scalar.return_value = Decimal("50.00")
            db.query.return_value = mock_query
            
            result = service.check_or_create_budget_notification(user.user_id)
            
            assert result == 0
            mock_create.assert_not_called()

    def test_deduplication_prevents_duplicate_alerts(self):
        """Verifies that duplicate notifications are not created within the same period."""
        db = MagicMock()
        user = make_user(spending_limit=Decimal("100.00"), threshold=80)
        service = BudgetService(db)
        
        with patch("app.services.budget_service.get_user_by_id", return_value=user), \
             patch("app.services.budget_service.get_period_dates", return_value=(
                 datetime(2026, 3, 1, tzinfo=timezone.utc), datetime(2026, 3, 31, tzinfo=timezone.utc)
             )), \
             patch("app.services.notification_service.NotificationService.create_notification") as mock_create:
            
            mock_query = MagicMock()
            mock_query.filter.return_value.scalar.return_value = Decimal("85.00")
            db.query.return_value = mock_query
            
            service._alert_already_sent = MagicMock(return_value=True)
            
            result = service.check_or_create_budget_notification(user.user_id)
            
            assert result == 0
            mock_create.assert_not_called()


# ══════════════════════════════════════════════════════════════════════════════
# TestGetBudgetAlerts
# ══════════════════════════════════════════════════════════════════════════════

class TestGetBudgetAlerts:
    def test_maps_notifications_to_alerts_correctly(self):
        """Validates that unread notifications are correctly mapped to BudgetAlertResponse objects."""
        db = MagicMock()
        service = BudgetService(db)
        
        test_uuid = uuid.uuid4()
        mock_notif = MagicMock(spec=Notification)
        mock_notif.data = {"budget_id": str(test_uuid), "bill_name": "Netflix"}
        mock_notif.message = "Test message"
        mock_notif.type = MagicMock()
        mock_notif.type.value = "budget_alert"
        mock_notif.priority = MagicMock()
        mock_notif.priority.value = "normal"
        
        mock_query = MagicMock()
        mock_query.filter.return_value.order_by.return_value.all.return_value = [mock_notif]
        db.query.return_value = mock_query
        
        alerts = service.get_budget_alerts(uuid.uuid4())
        
        assert len(alerts) == 1
        assert alerts[0].bill_name == "Netflix"
        assert alerts[0].alert_type == "budget_alert"

    def test_handles_null_data_gracefully(self):
        """Ensures the method doesn't crash when notification.data is None."""
        db = MagicMock()
        service = BudgetService(db)
        
        mock_notif = MagicMock(spec=Notification)
        mock_notif.data = None
        mock_notif.message = "Fallback message"
        mock_notif.type = MagicMock()
        mock_notif.type.value = "bill_reminder"
        mock_notif.priority = None
        
        mock_query = MagicMock()
        mock_query.filter.return_value.order_by.return_value.all.return_value = [mock_notif]
        db.query.return_value = mock_query
        
        alerts = service.get_budget_alerts(uuid.uuid4())
        
        assert len(alerts) == 1
        assert alerts[0].budget_id is None
        assert alerts[0].priority == NotificationPriority.NORMAL

    def test_returns_empty_list_when_no_unread_notifications(self):
        """Returns an empty list when there are no unread notifications."""
        db = MagicMock()
        service = BudgetService(db)
        
        mock_query = MagicMock()
        mock_query.filter.return_value.order_by.return_value.all.return_value = []
        db.query.return_value = mock_query
        
        assert service.get_budget_alerts(uuid.uuid4()) == []


# ══════════════════════════════════════════════════════════════════════════════
# TestUpdateBudget
# ══════════════════════════════════════════════════════════════════════════════

class TestUpdateBudget:
    def test_update_normal_fields(self):
        """Tests that normal budget fields (like amount) can be updated successfully."""
        db = MagicMock()
        service = BudgetService(db)
        budget = make_budget()
        
        with patch("app.services.budget_service.get_budget_or_raise", return_value=budget):
            data = BudgetUpdate(amount=Decimal("200.00"))
            service.update_budget(uuid.uuid4(), budget.budget_id, data)
            
            assert budget.amount == Decimal("200.00")
            db.commit.assert_called_once()

    def test_update_bill_to_paid_advances_cycle(self):
        """Verifies that marking a bill as paid triggers the bill cycle advancement logic."""
        db = MagicMock()
        service = BudgetService(db)
        budget = make_budget(is_bill=True, status=BillStatus.PENDING)
        
        with patch("app.services.budget_service.get_budget_or_raise", return_value=budget), \
             patch("app.services.budget_service.advance_bill_cycle") as mock_advance:
            
            data = BudgetUpdate.model_validate({"status": "paid"}) 
            
            service.update_budget(uuid.uuid4(), budget.budget_id, data)
            
            mock_advance.assert_called_once_with(budget)
            db.commit.assert_called_once()